from enum import Enum

class ErrorCategory(str, Enum):
    SYSTEM = "SYSTEM"
    BRIDGE = "BRIDGE"
    AUTH = "AUTH"
    PROJECT = "PROJECT"
    CARD = "CARD"
    SESSION = "SESSION"
    PROVIDER = "PROVIDER"

class ErrorCode(str, Enum):
    # System Errors
    INTERNAL_ERROR = "SYSTEM:INTERNAL_ERROR"
    NOT_IMPLEMENTED = "SYSTEM:NOT_IMPLEMENTED"
    INVALID_PARAMS = "SYSTEM:INVALID_PARAMS"
    
    # Bridge Errors
    BRIDGE_TIMEOUT = "BRIDGE:TIMEOUT"
    BRIDGE_DISCONNECTED = "BRIDGE:DISCONNECTED"
    BRIDGE_UNAVAILABLE = "BRIDGE:UNAVAILABLE"
    
    # Auth Errors
    UNAUTHORIZED = "AUTH:UNAUTHORIZED"
    FORBIDDEN = "AUTH:FORBIDDEN"
    
    # Project Errors
    PROJECT_NOT_FOUND = "PROJECT:NOT_FOUND"
    PROJECT_ALREADY_EXISTS = "PROJECT:ALREADY_EXISTS"
    
    # Card Errors
    CARD_NOT_FOUND = "CARD:NOT_FOUND"
    CARD_ACCESS_DENIED = "CARD:ACCESS_DENIED"
    
    # Session Errors
    SESSION_NOT_FOUND = "SESSION:NOT_FOUND"
    SESSION_BUSY = "SESSION:BUSY"
    SESSION_EXPIRED = "SESSION:EXPIRED"
    
    # Provider Errors
    PROVIDER_ERROR = "PROVIDER:ERROR"
    PROVIDER_TIMEOUT = "PROVIDER:TIMEOUT"
    PROVIDER_QUOTA_EXCEEDED = "PROVIDER:QUOTA_EXCEEDED"
